# 必须配置，或在环境变量中配置也可
OPENAI_API_KEY: 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  # sk-XXXX更改为你的api key,可从此处获取 https://platform.openai.com/account/api-keys
PORT: 10003    # 运行端口

# 功能性配置，可适当调整
CHAT_CONTEXT_NUMBER_MAX: 7  # 连续对话模式下的上下文最大数量 n，即开启连续对话模式后，将上传本条消息以及之前你和GPT对话的n-1条消息
USER_SAVE_MAX: 12  # 设置最多存储12个用户，当用户过多时可适当调大